swagger: '2.0'
info:
  title: Subscription API
  version: 0.0.1
  description: Subscription API
basePath: /subscribe/v1
schemes:
  - https

tags:
  - name: open
    description: open methods
  - name: secure
    description: authorized user methods

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    name: X-Auth-Token
    in: header

consumes:
  - application/json
produces:
  - application/json

paths:
  /health-check:
    $ref: './methods/health_check.yml#/health_check'
  /auth-check:
    $ref: './methods/health_check.yml#/auth_check'

  /subscribe:
    $ref: 'methods/mailing.yml#/email_subscribe'