version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "8088:8088"
    depends_on:
      - graphite
    networks:
      - monitor

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    networks:
      - monitor

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
      - "2003:2003"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitor
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

networks:
  monitor: