server.port: 9000

spring:
    kafka:
        bootstrap-servers: localhost:19092,localhost:29092
        producer.properties:
            acks: 1
            batch.size: 1024
            linger.ms: 10000
            schema.registry.url: http://localhost:8083
            # transactional.id: custom-tx-id
    cloud.zookeeper:
        config.enabled: false
        connect-string: localhost:2181

springdoc.swagger-ui.path: /swagger-ui.html

app:
    user-events:
        topic: user-events
        avro-topic: user-events-avro
        partitions: 3
        replicas: 2
