version: '3.1'

services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: users
        ports:
            - "5432:5432"

    liquibase:
        image: liquibase/liquibase
        container_name: liquibase
        depends_on:
            - postgres
        volumes:
            - ../changelog:/liquibase/changelog
        command: [
            "update",
            "--url=jdbc:postgresql://postgres:5432/users",
            "--username=admin",
            "--password=admin",
            "--changeLogFile=changelog/db.changelog.sql" ]

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            # KAFKA_OPTS: "-Djava.security.auth.login.config=/tmp/jaas.conf"
        # volumes:
        #     - ./jaas/zookeeper_jaas.conf:/tmp/jaas.conf

    kafka-1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka
        container_name: kafka-1
        ports:
            - "19092:19092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,DOCKER://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            # KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            # KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            # KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            # KAFKA_OPTS: "-Djava.security.auth.login.config=/tmp/jaas.conf"
        depends_on:
            - zookeeper
        # volumes:
        #     - ./jaas/kafka_server_jaas.conf:/tmp/jaas.conf

    kafka-2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka
        container_name: kafka-2
        ports:
            - "29092:29092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,DOCKER://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 2
            # KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            # KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            # KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
            # KAFKA_OPTS: "-Djava.security.auth.login.config=/tmp/jaas.conf"
        depends_on:
            - zookeeper
        # volumes:
        #     - ./jaas/kafka_server_jaas.conf:/tmp/jaas.conf

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        ports:
            - "8082:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: 'true'
        volumes:
            - ./kui/config.yml:/etc/kafkaui/config.yaml
            - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
