services:
  # TODO: use same env var in services and in application.conf
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

  redis:
    image: redis:7.4
    restart: always
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: dummy
      MINIO_ROOT_PASSWORD: dummy1234
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 10; mc alias set myminio http://minio:9000 dummy dummy1234 --api S3v4; mc mb myminio/my-pet-service; mc cp rabbit.jpg myminio/my-pet-service; exit 0; "
    volumes:
      - ./../images/rabbit.jpg:/rabbit.jpg
  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
